# Generated by Django 4.0.6 on 2022-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='longurl',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=7),
        ),
    ]
